	# Skip signal monitoring to prevent Dictionary corruption
	# assert_signal(_action_panel).is_emitted("action_executed")  # REMOVED - causes Dictionary corruption
	# assert_signal(_action_panel).is_emitted("action_confirmed")  # REMOVED - causes Dictionary corruption
	# assert_signal(_action_panel).is_emitted("actions_loaded")  # REMOVED - causes Dictionary corruption
	# assert_signal(_action_panel).is_emitted("actions_updated")  # REMOVED - causes Dictionary corruption
	# assert_signal(_action_panel).is_emitted("panel_refreshed")  # REMOVED - causes Dictionary corruption
	# assert_signal(_action_panel).is_emitted("action_failed")  # REMOVED - causes Dictionary corruption
	# assert_signal(_action_panel).is_emitted("action_cancelled")  # REMOVED - causes Dictionary corruption
	# assert_signal(_action_panel).is_emitted("panel_closed")  # REMOVED - causes Dictionary corruption
	# Test state directly instead of signal emission 