extends FiveParsecsCampaignPanel

## Five Parsecs Equipment Generation Panel
## Production-ready implementation with comprehensive equipment systems

const StartingEquipmentGenerator = preload("res://src/core/character/Equipment/StartingEquipmentGenerator.gd")
const Character = preload("res://src/core/character/Character.gd")

# GlobalEnums available as autoload singleton

signal equipment_generated(equipment: Array[Dictionary])
@warning_ignore("unused_signal")
signal equipment_setup_complete(equipment_data: Dictionary)
# SPRINT ENHANCEMENT: Backend integration signal
signal equipment_requested(crew_data: Array)

# Autonomous signals for coordinator pattern
signal equipment_data_complete(data: Dictionary)
signal equipment_validation_failed(errors: Array[String])

# Granular signals for real-time integration
signal equipment_data_changed(data: Dictionary)
signal equipment_generation_complete(equipment: Array)

var local_equipment_data: Dictionary = {
	"equipment": [],
	"credits": 0,
	"is_complete": false
}

# UI Components with safe access
var equipment_list: VBoxContainer
var generate_button: Button
var reroll_button: Button
var manual_button: Button
var summary_label: Label
var credits_label: Label

var generated_equipment: Array[Dictionary] = []
var starting_credits: int = 0
var crew_size: int = 4
var dice_manager: Node # Add dice_manager reference

func _on_campaign_state_updated(state_data: Dictionary) -> void:
	"""Override from interface - handle campaign state updates"""
	# Update panel state based on campaign state if needed
	if state_data.has("equipment") and state_data.equipment is Dictionary:
		var equipment_state_data = state_data.equipment
		if equipment_state_data.has("credits"):
			# Update local equipment state from external changes
			starting_credits = equipment_state_data.credits
			_update_display()

func _ready() -> void:
	# Set panel info before base initialization
	set_panel_info("Equipment Generation", "Generate starting equipment and credits for your crew based on their backgrounds.")
	
	# Call parent _ready() to initialize BaseCampaignPanel structure
	super._ready()
	
	# Initialize equipment-specific functionality
	call_deferred("_initialize_components")

func _setup_panel_content() -> void:
	"""Override from BaseCampaignPanel - setup equipment-specific content"""
	# This will be called after BaseCampaignPanel structure is ready
	pass

func _initialize_components() -> void:
	"""Initialize equipment panel with safe component access"""
	equipment_list = get_node("Content/EquipmentList/Container")
	generate_button = get_node("Content/Controls/GenerateButton")
	reroll_button = get_node("Content/Controls/RerollButton")
	manual_button = get_node("Content/Controls/ManualButton")
	summary_label = get_node("Content/Summary/Label")
	credits_label = get_node("Content/Credits/Value")

	# Get DiceManager from autoload
	if has_node("/root/DiceManager"):
		dice_manager = get_node("/root/DiceManager")
	else:
		push_warning("EquipmentGenerationPanel: DiceManager not found!")

	_connect_signals()
	_generate_starting_equipment()
	call_deferred("_emit_panel_ready")

func _connect_signals() -> void:
	"""Establish signal connections with error handling"""
	if generate_button:
		generate_button.pressed.connect(_on_generate_pressed)
	if reroll_button:
		reroll_button.pressed.connect(_on_reroll_equipment_pressed)
	if manual_button:
		manual_button.pressed.connect(_on_manual_select_pressed)

func set_crew_data(crew: Array[Character]) -> void:
	"""Set crew data and generate equipment"""
	# This is the intended entry point from the campaign wizard
	crew_size = crew.size()
	_generate_starting_equipment(crew)

# SPRINT ENHANCEMENT: Backend integration methods
func request_equipment_generation(crew_data: Array) -> void:
	"""Request equipment generation through backend systems"""
	print("EquipmentPanel: Requesting equipment generation for %d crew members via backend" % crew_data.size())
	equipment_requested.emit(crew_data)

func set_generated_equipment(equipment: Array, credits: int) -> void:
	"""Receive equipment generated by backend systems"""
	print("EquipmentPanel: Received %d equipment items, %d credits from backend" % [equipment.size(), credits])
	generated_equipment = equipment
	starting_credits = credits
	_update_equipment_display()
	_update_summary()
	equipment_generated.emit(generated_equipment)
	
	# Emit granular signal for real-time integration
	equipment_data_changed.emit(get_data())
	_validate_and_complete()

func _generate_starting_equipment(crew: Array[Character] = []) -> void:
	"""Generate starting equipment using StartingEquipmentGenerator"""
	generated_equipment.clear()
	starting_credits = 0

	var current_crew: Array[Character] = crew
	if current_crew.is_empty():
		# If no crew is passed, create a mock crew for demonstration
		current_crew = _create_mock_crew()

	# Generate equipment for each character
	for character: Character in current_crew:
		var char_equipment: Dictionary = StartingEquipmentGenerator.generate_starting_equipment(character, dice_manager)
		StartingEquipmentGenerator.apply_equipment_condition(char_equipment, dice_manager)
		
		# Merge equipment into a single list
		for weapon: Dictionary in char_equipment.get("weapons", []):
			weapon["type"] = "Weapon"
			weapon["owner"] = character.character_name
			generated_equipment.append(weapon)
			
		for armor_item: Dictionary in char_equipment.get("armor", []):
			armor_item["type"] = "Armor"
			armor_item["owner"] = character.character_name
			generated_equipment.append(armor_item)

		for gear_item: Dictionary in char_equipment.get("gear", []):
			gear_item["type"] = "Gear"
			gear_item["owner"] = character.character_name
			generated_equipment.append(gear_item)
		
		starting_credits += char_equipment.get("credits", 0)

	_update_equipment_display()
	_update_summary()
	equipment_generated.emit(generated_equipment)
	
	# Emit granular signal for real-time integration
	equipment_data_changed.emit(get_data())
	_validate_and_complete()

func _create_mock_crew() -> Array[Character]:
	"""Creates a mock crew for testing and demonstration purposes"""
	var mock_crew: Array[Character] = []
	var class_names: Array = GlobalEnums.CharacterClass.keys()
	var background_names: Array = GlobalEnums.Background.keys()
	
	for i in range(crew_size):
		var new_char: Character = Character.new()
		new_char.character_name = "Crew Member %d" % (i + 1)
		
		# Assign random class and background, skipping the 'NONE' enum at index 0
		var random_class_name: String = class_names[1 + randi() % (class_names.size() - 1)]
		new_char.character_class = GlobalEnums.CharacterClass[random_class_name]
		
		var random_bg_name: String = background_names[1 + randi() % (background_names.size() - 1)]
		new_char.background = GlobalEnums.Background[random_bg_name]
		
		mock_crew.append(new_char)
		
	return mock_crew

func _update_summary() -> void:
	"""Update equipment summary and credits display"""
	if summary_label:
		summary_label.text = "Equipment generated for %d crew members: %d items" % [crew_size, generated_equipment.size()]

	if credits_label:
		credits_label.text = str(starting_credits)

# Signal handlers
func _on_generate_pressed() -> void:
	_generate_starting_equipment()

func _on_reroll_equipment_pressed() -> void:
	_generate_starting_equipment()

func _on_manual_select_pressed() -> void:
	"""Show manual equipment selection - implement based on UI architecture"""
	print("Manual equipment selection not yet implemented")

# get_equipment_data() function moved to line 336

func is_setup_complete() -> bool:
	"""Check if equipment setup is complete"""
	return generated_equipment.size() > 0

func _update_equipment_display() -> void:
	"""Update the equipment list display"""
	if equipment_list:
		for child in equipment_list.get_children():
			child.queue_free()

		for item: Dictionary in generated_equipment:
			var item_container: HBoxContainer = HBoxContainer.new()
			
			var name_label: Label = Label.new()
			name_label.text = item.get("name", "Unknown Item")
			name_label.custom_minimum_size.x = 200
			item_container.add_child(name_label)
			
			var type_label: Label = Label.new()
			type_label.text = item.get("type", "Misc")
			type_label.custom_minimum_size.x = 100
			item_container.add_child(type_label)
			
			var condition_label: Label = Label.new()
			var condition: String = item.get("condition", "standard")
			condition_label.text = "Condition: %s" % condition.capitalize()
			condition_label.custom_minimum_size.x = 180
			item_container.add_child(condition_label)
			
			var owner_label: Label = Label.new()
			owner_label.text = "For: %s" % item.get("owner", "Crew")
			owner_label.size_flags_horizontal = Control.SIZE_EXPAND_FILL
			item_container.add_child(owner_label)
			
			equipment_list.add_child(item_container)

func validate() -> Array[String]:
	"""Validate equipment data and return error messages"""
	var validation = validate_panel()
	return validation.errors if validation.errors else []

func set_data(data: Dictionary) -> void:
	"""Set panel data - generic interface method"""
	if data.has("crew"):
		var crew: Array[Character] = data.get("crew", [])
		set_crew_data(crew)
	elif data.has("crew_size"):
		crew_size = data.crew_size
		_generate_starting_equipment()

## Safe method call helper - eliminates UNSAFE_METHOD_ACCESS warnings
func safe_call_method(obj: Node, method_name: String, args: Array = []):
	if obj == null:
		return null
	if obj is Object and obj.has_method(method_name):
		return obj.callv(method_name, args)
	return null

# --- Additions to EquipmentPanel.gd ---

func _validate_and_complete() -> void:
	local_equipment_data.equipment = generated_equipment
	local_equipment_data.credits = starting_credits
	
	# Validate equipment data
	var errors = validate()
	if not errors.is_empty():
		local_equipment_data.is_complete = false
		validation_failed.emit(errors)
		equipment_validation_failed.emit(errors)
		return
	
	local_equipment_data.is_complete = true

	# Emit panel data update for signal-based architecture (no arguments needed)
	panel_data_changed.emit()
	
	# Emit granular data change signal for real-time integration
	equipment_data_changed.emit(get_data())

	# Emit completion signal if the panel is valid
	if local_equipment_data.is_complete:
		panel_completed.emit(get_data())
		equipment_data_complete.emit(get_data())
		equipment_generation_complete.emit(generated_equipment)

func get_data() -> Dictionary:
	"""Get panel data - generic interface method"""
	var data = get_equipment_data()
	data["is_complete"] = local_equipment_data.is_complete
	return data

## Required Interface Methods from ICampaignCreationPanel

func validate_panel() -> ValidationResult:
	"""Validate panel data and return ValidationResult"""
	var result = ValidationResult.new()
	var errors = _validate_equipment_data()
	
	if errors.is_empty():
		result.valid = true
		result.sanitized_value = get_equipment_data()
	else:
		result.valid = false
		result.error = errors[0] if errors.size() > 0 else "Equipment validation failed"
		# Add additional errors as warnings since ValidationResult only has one error field
		for i in range(1, errors.size()):
			result.add_warning(errors[i])
	
	return result

func get_panel_data() -> Dictionary:
	"""Get panel data - interface implementation"""
	return get_equipment_data()

func reset_panel() -> void:
	"""Reset panel to default state"""
	generated_equipment.clear()
	starting_credits = 0
	crew_size = 4
	local_equipment_data = {
		"equipment": [],
		"credits": 0,
		"is_complete": false
	}
	
	_update_display()

func _validate_equipment_data() -> Array[String]:
	"""Validate equipment data and return array of error messages"""
	var errors: Array[String] = []
	
	# Basic validation - equipment generation is optional but if present, should be valid
	if generated_equipment.size() > 0:
		for item in generated_equipment:
			if not item.has("name") or item.name.strip_edges().is_empty():
				errors.append("All equipment items must have valid names")
				break
	
	# Credits should not be negative
	if starting_credits < 0:
		errors.append("Starting credits cannot be negative")
	
	return errors

func get_equipment_data() -> Dictionary:
	"""Get equipment data in standardized format"""
	return {
		"equipment": generated_equipment.duplicate(),
		"starting_credits": starting_credits,
		"crew_size": crew_size,
		"is_complete": local_equipment_data.is_complete,
		"metadata": {
			"last_modified": Time.get_unix_time_from_system(),
			"version": "1.0",
			"panel_type": "equipment_generation"
		}
	}

## Panel Data Persistence Implementation

func restore_panel_data(data: Dictionary) -> void:
	"""Restore panel data from persistence system"""
	if data.is_empty():
		print("EquipmentPanel: No data to restore")
		return
	
	print("EquipmentPanel: Restoring panel data: ", data.keys())
	
	# Restore equipment data
	if data.has("equipment"):
		generated_equipment = data.equipment.duplicate() if data.equipment is Array else []
	
	# Restore credits
	if data.has("starting_credits"):
		starting_credits = data.starting_credits
	
	# Restore crew size
	if data.has("crew_size"):
		crew_size = data.crew_size
	
	# Restore completion status
	if data.has("is_complete"):
		local_equipment_data.is_complete = data.is_complete
	
	print("EquipmentPanel: Restored %d equipment items, %d credits" % [generated_equipment.size(), starting_credits])
	
	# Update UI with restored data
	_update_display()
	
	# Emit signal
	if not generated_equipment.is_empty():
		equipment_generated.emit(generated_equipment)
	
	print("EquipmentPanel: Panel data restoration complete")

func _update_display() -> void:
	"""Update all UI displays - used by both testing and production"""
	_update_equipment_display()
	_update_summary()

# --- End of additions ---
