# GlobalEnums.gd
class_name GlobalEnums
extends Node

enum Race { HUMAN, ENGINEER, KERIN, SOULLESS, PRECURSOR, FERAL, SWIFT, BOT, SKULKER, KRAG }
enum Background { HIGH_TECH_COLONY, OVERCROWDED_CITY, LOW_TECH_COLONY, MINING_COLONY, MILITARY_BRAT, SPACE_STATION }
enum Motivation { WEALTH, FAME, GLORY, SURVIVAL, ESCAPE, ADVENTURE }
enum Class { WORKING_CLASS, TECHNICIAN, SCIENTIST, HACKER, SOLDIER, MERCENARY }

enum PsionicPower { 
	BARRIER,
	GRAB,
	LIFT,
	SHROUD,
	ENRAGE,
	PREDICT,
	SHOCK,
	REJUVENATE,
	GUIDE,
	PSIONIC_SCARE
}

enum PsionicLegality { LEGAL, RESTRICTED, ILLEGAL }
