class_name GlobalEnums
extends Resource

enum Species { HUMAN, ENGINEER, KERIN, SOULLESS, PRECURSOR, FERAL, SWIFT, BOT, SKULKER, KRAG }
enum Background { HIGH_TECH_COLONY, OVERCROWDED_CITY, LOW_TECH_COLONY, MINING_COLONY, MILITARY_BRAT, SPACE_STATION }
enum Motivation { WEALTH, FAME, GLORY, SURVIVAL, ESCAPE, ADVENTURE }
enum Class { WORKING_CLASS, TECHNICIAN, SCIENTIST, HACKER, SOLDIER, MERCENARY }

enum PsionicPower { 
    BARRIER,
    GRAB,
    LIFT,
    SHROUD,
    ENRAGE,
    PREDICT,
    SHOCK,
    REJUVENATE,
    GUIDE,
    PSIONIC_SCARE
    # Ensure this matches your Psionics.json file
}

enum PsionicLegality { LEGAL, RESTRICTED, ILLEGAL }

enum WeaponType { PISTOL, RIFLE, HEAVY, MELEE, GRENADE }
enum ArmorType { LIGHT, MEDIUM, HEAVY, SCREEN }
enum MissionType { PATROL, RESCUE, SABOTAGE, ESCORT, ASSASSINATION, RETRIEVAL }
enum TerrainType { URBAN, WILDERNESS, SPACE_STATION, STARSHIP, ALIEN_WORLD }
enum CampaignPhase { UPKEEP, STORY_POINT, TRAVEL, PATRONS, MISSION, BATTLE, POST_BATTLE }
enum CharacterStatus { ACTIVE, INJURED, DEAD }
enum SkillType { COMBAT, TECHNICAL, SOCIAL, SURVIVAL }
enum ItemRarity { COMMON, UNCOMMON, RARE, UNIQUE }
enum FactionType { NEUTRAL, FRIENDLY, HOSTILE }
enum BattleOutcome { VICTORY, DEFEAT, DRAW }
enum ShipUpgrade { ENGINE, WEAPONS, SHIELDS, CARGO, LIVING_QUARTERS }

enum StrifeType { RESOURCE_CONFLICT, POLITICAL_UPRISING, ALIEN_INCURSION, CORPORATE_WARFARE }

enum ComponentType {
    HULL,
    ENGINE,
    WEAPONS,
    MEDICAL_BAY,
    SHIELDS,
    CARGO_HOLD,
    DROP_POD,
    SHUTTLE_BAY
}

enum Type {
    INFILTRATION,
    STREET_FIGHT,
    SALVAGE_JOB,
    FRINGE_WORLD_STRIFE,
    OPPORTUNITY,
    PATRON,
    QUEST,
    RIVAL,
    TUTORIAL
}