blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/Reptarus/five-parsecs-campaign-manager/issues
    about: For general questions, open a blank issue with the "question" label.
