class_name ContactMarkerPanel
extends PanelContainer

## Bug Hunt Contact Marker Tracker
## Displays scanner blips on a 4x4 sector grid with reveal, movement,
## and priority spawning controls. ASSISTED tier battle companion.

signal contact_revealed(marker_id: String, enemy_data: Dictionary)
signal contact_moved(marker_id: String, from_sector: Dictionary, to_sector: Dictionary)
signal priority_spawning_result(new_contacts: int)

const _UC = preload("res://src/ui/components/base/UIColors.gd")
const COLOR_BASE := _UC.COLOR_BASE
const COLOR_ELEVATED := _UC.COLOR_ELEVATED
const COLOR_TEXT := _UC.COLOR_TEXT_PRIMARY
const COLOR_TEXT_SEC := _UC.COLOR_TEXT_SECONDARY
const COLOR_BORDER := _UC.COLOR_BORDER
const COLOR_DANGER := _UC.COLOR_DANGER
const COLOR_WARNING := _UC.COLOR_WARNING
const COLOR_SUCCESS := _UC.COLOR_SUCCESS
const COLOR_BLIP := Color("#FF4444")  # Contact marker red (no UIColors equivalent)
const COLOR_CLEAR := Color("#333355")  # Empty grid cell (no UIColors equivalent)

var _contact_markers: Array = []
var _tactical_locations: Array = []
var _spawn_points: Array = []
var _battle_context: Dictionary = {}


func get_contact_markers() -> Array:
	return _contact_markers
var _encounter_count: int = 0

var _grid_labels: Array = []  # 4x4 array of Labels for sector display
var _marker_list: VBoxContainer
var _log_container: VBoxContainer
var _movie_magic_container: VBoxContainer
var _enemy_generator = null  # BugHuntEnemyGenerator
var _campaign_ref = null  # BugHuntCampaignCore for Movie Magic


func _ready() -> void:
	_build_ui()


func setup_bug_hunt(context: Dictionary, campaign = null) -> void:
	## Initialize from battle context generated by BugHuntBattleSetup.
	_battle_context = context
	_contact_markers = context.get("contact_markers", [])
	_tactical_locations = context.get("tactical_locations", [])
	_spawn_points = context.get("spawn_points", [])
	_encounter_count = 0
	_campaign_ref = campaign

	# Create enemy generator for reveal mechanics
	var BugHuntEnemyGen = load("res://src/core/systems/BugHuntEnemyGenerator.gd")
	if BugHuntEnemyGen:
		_enemy_generator = BugHuntEnemyGen.new()
		_enemy_generator.start_mission(context.get("priority", 1))

	_populate_movie_magic()
	_refresh_display()


func _build_ui() -> void:
	var style := StyleBoxFlat.new()
	style.bg_color = COLOR_ELEVATED
	style.border_color = COLOR_BORDER
	style.set_border_width_all(1)
	style.set_corner_radius_all(6)
	style.content_margin_left = 12
	style.content_margin_right = 12
	style.content_margin_top = 8
	style.content_margin_bottom = 8
	add_theme_stylebox_override("panel", style)

	var vbox := VBoxContainer.new()
	vbox.add_theme_constant_override("separation", 8)
	add_child(vbox)

	# Title
	var title := Label.new()
	title.text = "CONTACT TRACKER"
	title.add_theme_font_size_override("font_size", 16)
	title.add_theme_color_override("font_color", COLOR_TEXT)
	title.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	vbox.add_child(title)

	# 4x4 sector grid
	var grid := GridContainer.new()
	grid.columns = 4
	grid.add_theme_constant_override("h_separation", 4)
	grid.add_theme_constant_override("v_separation", 4)
	vbox.add_child(grid)

	_grid_labels.clear()
	for r in range(4):
		var row: Array = []
		for c in range(4):
			var cell := Label.new()
			cell.text = "·"
			cell.add_theme_font_size_override("font_size", 18)
			cell.add_theme_color_override("font_color", COLOR_CLEAR)
			cell.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
			cell.custom_minimum_size = Vector2(36, 28)
			grid.add_child(cell)
			row.append(cell)
		_grid_labels.append(row)

	# Action buttons
	var btn_box := HBoxContainer.new()
	btn_box.add_theme_constant_override("separation", 6)
	vbox.add_child(btn_box)

	var move_btn := Button.new()
	move_btn.text = "Move Contact"
	move_btn.tooltip_text = "Roll Aggression vs Chance dice (Compendium p.192)"
	move_btn.custom_minimum_size.y = 32
	move_btn.pressed.connect(_on_move_contact)
	btn_box.add_child(move_btn)

	var roll_contact_btn := Button.new()
	roll_contact_btn.text = "Detect"
	roll_contact_btn.tooltip_text = "Roll on Contact Table D6 (Compendium p.193)"
	roll_contact_btn.custom_minimum_size.y = 32
	roll_contact_btn.pressed.connect(_on_roll_contact)
	btn_box.add_child(roll_contact_btn)

	var spawn_btn := Button.new()
	spawn_btn.text = "Priority Spawn"
	spawn_btn.tooltip_text = "Beep... Sir? — D6 per Priority (Compendium p.193)"
	spawn_btn.custom_minimum_size.y = 32
	spawn_btn.pressed.connect(_on_priority_spawning)
	btn_box.add_child(spawn_btn)

	# Second row: tactical & spawn point helpers
	var btn_box2 := HBoxContainer.new()
	btn_box2.add_theme_constant_override("separation", 6)
	vbox.add_child(btn_box2)

	var tac_btn := Button.new()
	tac_btn.text = "Activate TacLoc"
	tac_btn.tooltip_text = "1D6+Savvy >= 5+ (Compendium p.191)"
	tac_btn.custom_minimum_size.y = 32
	tac_btn.pressed.connect(_on_activate_tactical)
	btn_box2.add_child(tac_btn)

	var close_spawn_btn := Button.new()
	close_spawn_btn.text = "Close Spawn"
	close_spawn_btn.tooltip_text = "1D6+Savvy >= 6+ to seal a Spawn Point (Compendium p.200)"
	close_spawn_btn.custom_minimum_size.y = 32
	close_spawn_btn.pressed.connect(_on_close_spawn_point)
	btn_box2.add_child(close_spawn_btn)

	var evac_btn := Button.new()
	evac_btn.text = "Request Evac"
	evac_btn.tooltip_text = "2D6 + objectives + packages (need 10+, Compendium p.201)"
	evac_btn.custom_minimum_size.y = 32
	evac_btn.pressed.connect(_on_request_evac)
	btn_box2.add_child(evac_btn)

	# Movie Magic section
	_movie_magic_container = VBoxContainer.new()
	_movie_magic_container.add_theme_constant_override("separation", 4)
	vbox.add_child(_movie_magic_container)

	# Formation check button
	var btn_box3 := HBoxContainer.new()
	btn_box3.add_theme_constant_override("separation", 6)
	vbox.add_child(btn_box3)

	var signal_btn := Button.new()
	signal_btn.text = "Investigate Signal"
	signal_btn.tooltip_text = "D6 Signal table (optional rule, Compendium p.208)"
	signal_btn.custom_minimum_size.y = 32
	signal_btn.pressed.connect(_on_investigate_signal)
	btn_box3.add_child(signal_btn)

	var formation_btn := Button.new()
	formation_btn.text = "Formation?"
	formation_btn.tooltip_text = "Combat teams in formation (all within 2\") get +1 Reactions (Compendium p.173)"
	formation_btn.custom_minimum_size.y = 32
	formation_btn.pressed.connect(func():
		_add_log("FORMATION CHECK: If all team members within 2\" of selected figure → +1 Reactions this round.")
	)
	btn_box3.add_child(formation_btn)

	# Marker list
	_marker_list = VBoxContainer.new()
	_marker_list.add_theme_constant_override("separation", 4)
	vbox.add_child(_marker_list)

	# Log
	_log_container = VBoxContainer.new()
	_log_container.add_theme_constant_override("separation", 2)
	vbox.add_child(_log_container)


func _refresh_display() -> void:
	# Reset grid
	for r in range(4):
		for c in range(4):
			if r < _grid_labels.size() and c < _grid_labels[r].size():
				var cell: Label = _grid_labels[r][c]
				cell.text = "·"
				cell.add_theme_color_override("font_color", COLOR_CLEAR)

	# Place contact markers
	for marker in _contact_markers:
		if marker is not Dictionary:
			continue
		var sector: Dictionary = marker.get("sector", {})
		var row: int = sector.get("row", 0)
		var col: int = sector.get("col", 0)
		if row < _grid_labels.size() and col < _grid_labels[row].size():
			var cell: Label = _grid_labels[row][col]
			if marker.get("revealed", false):
				cell.text = "X"
				cell.add_theme_color_override("font_color", COLOR_DANGER)
			else:
				cell.text = "?"
				cell.add_theme_color_override("font_color", COLOR_BLIP)

	# Place tactical locations
	for loc in _tactical_locations:
		if loc is not Dictionary:
			continue
		var sector: Dictionary = loc.get("sector", {})
		var row: int = sector.get("row", 0)
		var col: int = sector.get("col", 0)
		if row < _grid_labels.size() and col < _grid_labels[row].size():
			var cell: Label = _grid_labels[row][col]
			if cell.text == "·":
				cell.text = "T"
				cell.add_theme_color_override("font_color", COLOR_SUCCESS)

	# Update marker list
	for child in _marker_list.get_children():
		child.queue_free()

	for marker in _contact_markers:
		if marker is not Dictionary:
			continue
		var lbl := Label.new()
		var sector: Dictionary = marker.get("sector", {})
		if marker.get("revealed", false):
			lbl.text = "%s: REVEALED — %s (x%d)" % [
				marker.get("id", "?"),
				marker.get("enemy_type", "Unknown"),
				marker.get("enemy_count", 0)]
			lbl.add_theme_color_override("font_color", COLOR_DANGER)
		else:
			lbl.text = "%s: Sector (%d,%d) — Unidentified" % [
				marker.get("id", "?"),
				sector.get("row", 0), sector.get("col", 0)]
			lbl.add_theme_color_override("font_color", COLOR_WARNING)
		lbl.add_theme_font_size_override("font_size", 12)
		_marker_list.add_child(lbl)


var _battle_companion = null
var _tac_loc_failures: Dictionary = {}  # tac_loc_id -> failure_count
var _objectives_completed: int = 0


func _ensure_companion() -> void:
	if _battle_companion == null:
		var CompanionClass = load("res://src/core/battle/BugHuntBattleCompanion.gd")
		if CompanionClass:
			_battle_companion = CompanionClass.new()


func set_objectives_completed(count: int) -> void:
	_objectives_completed = count


func _on_move_contact() -> void:
	## Roll Aggression vs Chance dice for contact marker movement (Compendium p.192).
	_ensure_companion()
	if not _battle_companion:
		_add_log("Battle companion not available")
		return

	var result: Dictionary = _battle_companion.roll_contact_movement()
	_add_log(result.description)

	# Apply movement to a random unrevealed marker
	if result.result == "equal":
		# Place new contact on top of existing
		_add_contact_marker()
	else:
		_move_random_marker()


func _on_roll_contact() -> void:
	## Roll on the D6 contact table when a marker is detected (Compendium p.193).
	if not _enemy_generator:
		_add_log("No enemy generator available")
		return

	var contact_result: Dictionary = _enemy_generator.roll_contact_table()
	var roll: int = contact_result.get("roll", 0)
	var entry: Dictionary = contact_result.get("result", {})
	var result_type: String = entry.get("type", "stay_frosty")

	match result_type:
		"stay_frosty":
			_add_log("D6=%d: Stay frosty — remove marker. If < 3 markers, place new on far edge." % roll)
			_remove_unrevealed_marker()
			if _count_unrevealed() < 3:
				_add_contact_marker()
				_add_log("  (< 3 markers — new contact placed on far edge)")
		"movement":
			_add_log("D6=%d: Movement all over — move marker 1D6\" away, new marker on nearest edge." % roll)
			_move_random_marker()
			_add_contact_marker()
		"contact", _:
			_add_log("D6=%d: CONTACT! Enemies revealed!" % roll)
			_reveal_next_marker()


func _on_activate_tactical() -> void:
	## Roll 1D6+Savvy to activate a Tactical Location (Compendium p.191).
	_ensure_companion()
	if not _battle_companion:
		return
	# Use default Savvy 0 — player should mentally add their character's Savvy
	var savvy: int = 0  # Display prompt for player to enter
	var loc_id: String = "tac_loc"
	var failures: int = _tac_loc_failures.get(loc_id, 0)
	var result: Dictionary = _battle_companion.roll_tactical_activation(savvy, failures)
	if not result.success:
		_tac_loc_failures[loc_id] = failures + 1
	_add_log("TacLoc: " + result.description + " (Add your Savvy to the roll)")


func _on_close_spawn_point() -> void:
	## Roll 1D6+Savvy to close a Spawn Point (Compendium p.200).
	_ensure_companion()
	if not _battle_companion:
		return
	var result: Dictionary = _battle_companion.roll_close_spawn_point(0, false)
	_add_log("Spawn: " + result.description + " (Add your Savvy to the roll)")
	if result.success:
		# Remove a spawn point from tracking
		if not _spawn_points.is_empty():
			_spawn_points.pop_back()


func _on_investigate_signal() -> void:
	## Roll on Signal table D6 (optional rule, Compendium p.208).
	_ensure_companion()
	if not _battle_companion:
		_add_log("Battle companion not available")
		return
	var result: Dictionary = _battle_companion.roll_signal_investigation()
	_add_log("Signal D6=%d: %s" % [result.roll, result.description])


func _on_request_evac() -> void:
	## Roll for Evac (Compendium p.201). 2D6 + objectives + packages >= 10.
	_ensure_companion()
	if not _battle_companion:
		return
	var result: Dictionary = _battle_companion.roll_evac(_objectives_completed, 0, 0)
	_add_log("Evac: " + result.description + " (Add packages + Savvy bonus)")


func _on_priority_spawning() -> void:
	## Roll Priority Spawning dice (D6s equal to Priority).
	var priority: int = _battle_context.get("priority", 1)
	if not _enemy_generator:
		_add_log("No enemy generator available")
		return

	var new_contacts: int = _enemy_generator.roll_priority_spawning(priority)

	if new_contacts > 0:
		_add_log("Priority Spawning: %d new contact(s)!" % new_contacts)
		for i in range(new_contacts):
			_add_contact_marker()
		priority_spawning_result.emit(new_contacts)
	else:
		_add_log("Priority Spawning: All clear")


func _reveal_next_marker() -> void:
	for marker in _contact_markers:
		if marker is Dictionary and not marker.get("revealed", false):
			marker.revealed = true
			_encounter_count += 1

			if _enemy_generator:
				var reveal: Dictionary = _enemy_generator.reveal_contact(_encounter_count)
				var enemy_name: String = reveal.get("enemy_type", {}).get("name", "Unknown Hostiles")
				var enemy_count: int = reveal.get("count", 0)
				marker.enemy_type = enemy_name
				marker.enemy_count = enemy_count
				contact_revealed.emit(marker.get("id", ""), reveal)
				_add_log("REVEALED: %s — %d x %s" % [
					marker.get("id", "?"), enemy_count, enemy_name])
			else:
				_add_log("REVEALED: %s (no enemy data)" % marker.get("id", "?"))

			_refresh_display()
			return

	_add_log("No unrevealed markers remaining")


func _move_random_marker() -> void:
	var unrevealed: Array = []
	for marker in _contact_markers:
		if marker is Dictionary and not marker.get("revealed", false):
			unrevealed.append(marker)

	if unrevealed.is_empty():
		return

	var marker: Dictionary = unrevealed[randi() % unrevealed.size()]
	var old_sector: Dictionary = marker.get("sector", {})
	var new_row: int = clampi(old_sector.get("row", 0) + (randi() % 3) - 1, 0, 3)
	var new_col: int = clampi(old_sector.get("col", 0) + (randi() % 3) - 1, 0, 3)
	marker.sector = {"row": new_row, "col": new_col}

	contact_moved.emit(marker.get("id", ""), old_sector, marker.sector)
	_refresh_display()


func _add_contact_marker() -> void:
	var new_id: String = "contact_%d" % (_contact_markers.size() + 1)
	# Spawn from a random edge
	var edge: int = randi() % 4
	var sector: Dictionary
	match edge:
		0: sector = {"row": 0, "col": randi() % 4}
		1: sector = {"row": randi() % 4, "col": 3}
		2: sector = {"row": 3, "col": randi() % 4}
		_: sector = {"row": randi() % 4, "col": 0}

	_contact_markers.append({
		"id": new_id,
		"sector": sector,
		"revealed": false,
		"enemy_type": "",
		"enemy_count": 0
	})
	_refresh_display()


func _populate_movie_magic() -> void:
	## Build Movie Magic activation buttons (Compendium pp.181-182).
	## Each ability can only be used once per campaign.
	if not _movie_magic_container:
		return
	for child in _movie_magic_container.get_children():
		child.queue_free()

	if not _campaign_ref or not _campaign_ref.has_method("get_available_movie_magic"):
		return

	var available: Array = _campaign_ref.get_available_movie_magic()
	if available.is_empty():
		return

	var title := Label.new()
	title.text = "MOVIE MAGIC"
	title.add_theme_font_size_override("font_size", 14)
	title.add_theme_color_override("font_color", COLOR_WARNING)
	title.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	_movie_magic_container.add_child(title)

	# Load ability descriptions from JSON
	var abilities: Dictionary = {}
	var file := FileAccess.open("res://data/bug_hunt/bug_hunt_movie_magic.json", FileAccess.READ)
	if file:
		var json := JSON.new()
		if json.parse(file.get_as_text()) == OK and json.data is Dictionary:
			for ability in json.data.get("abilities", []):
				if ability is Dictionary:
					abilities[ability.get("id", "")] = ability
		file.close()

	for ability_id in available:
		var ability_data: Dictionary = abilities.get(ability_id, {})
		var ability_name: String = ability_data.get("name", ability_id.replace("_", " ").capitalize())
		var timing: String = ability_data.get("timing", "")
		var effect: String = ability_data.get("effect", "")

		var btn := Button.new()
		btn.text = ability_name
		btn.tooltip_text = "%s\n%s" % [timing, effect]
		btn.custom_minimum_size = Vector2(0, 28)
		btn.add_theme_font_size_override("font_size", 11)

		var id_ref: String = ability_id
		var btn_ref: Button = btn
		var name_ref := ability_name
		btn.pressed.connect(func():
			if _campaign_ref and _campaign_ref.has_method("use_movie_magic"):
				if _campaign_ref.use_movie_magic(id_ref):
					_add_log("MOVIE MAGIC: %s activated! — %s" % [name_ref, effect])
					btn_ref.text = "%s (USED)" % name_ref
					btn_ref.disabled = true
				else:
					_add_log("Movie Magic: %s already used this campaign." % name_ref)
		)
		_movie_magic_container.add_child(btn)


func _remove_unrevealed_marker() -> void:
	for i in range(_contact_markers.size() - 1, -1, -1):
		var marker = _contact_markers[i]
		if marker is Dictionary and not marker.get("revealed", false):
			_contact_markers.remove_at(i)
			_refresh_display()
			return


func _count_unrevealed() -> int:
	var count: int = 0
	for marker in _contact_markers:
		if marker is Dictionary and not marker.get("revealed", false):
			count += 1
	return count


func _add_log(text: String) -> void:
	var lbl := Label.new()
	lbl.text = "> " + text
	lbl.add_theme_font_size_override("font_size", 11)
	lbl.add_theme_color_override("font_color", COLOR_TEXT_SEC)
	lbl.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	_log_container.add_child(lbl)

	# Keep log manageable
	while _log_container.get_child_count() > 8:
		_log_container.get_child(0).queue_free()
