class_name ContactMarkerPanel
extends PanelContainer

## Bug Hunt Contact Marker Tracker
## Displays scanner blips on a 4x4 sector grid with reveal, movement,
## and priority spawning controls. ASSISTED tier battle companion.

signal contact_revealed(marker_id: String, enemy_data: Dictionary)
signal contact_moved(marker_id: String, from_sector: Dictionary, to_sector: Dictionary)
signal priority_spawning_result(new_contacts: int)

const COLOR_BASE := Color("#1A1A2E")
const COLOR_ELEVATED := Color("#252542")
const COLOR_TEXT := Color("#E0E0E0")
const COLOR_TEXT_SEC := Color("#808080")
const COLOR_BORDER := Color("#3A3A5C")
const COLOR_DANGER := Color("#DC2626")
const COLOR_WARNING := Color("#D97706")
const COLOR_SUCCESS := Color("#10B981")
const COLOR_BLIP := Color("#FF4444")
const COLOR_CLEAR := Color("#333355")

var _contact_markers: Array = []
var _tactical_locations: Array = []
var _spawn_points: Array = []
var _battle_context: Dictionary = {}


func get_contact_markers() -> Array:
	return _contact_markers
var _encounter_count: int = 0

var _grid_labels: Array = []  # 4x4 array of Labels for sector display
var _marker_list: VBoxContainer
var _log_container: VBoxContainer
var _enemy_generator = null  # BugHuntEnemyGenerator


func _ready() -> void:
	_build_ui()


func setup_bug_hunt(context: Dictionary) -> void:
	## Initialize from battle context generated by BugHuntBattleSetup.
	_battle_context = context
	_contact_markers = context.get("contact_markers", [])
	_tactical_locations = context.get("tactical_locations", [])
	_spawn_points = context.get("spawn_points", [])
	_encounter_count = 0

	# Create enemy generator for reveal mechanics
	var BugHuntEnemyGen = load("res://src/core/systems/BugHuntEnemyGenerator.gd")
	if BugHuntEnemyGen:
		_enemy_generator = BugHuntEnemyGen.new()
		_enemy_generator.start_mission(context.get("priority", 1))

	_refresh_display()


func _build_ui() -> void:
	var style := StyleBoxFlat.new()
	style.bg_color = COLOR_ELEVATED
	style.border_color = COLOR_BORDER
	style.set_border_width_all(1)
	style.set_corner_radius_all(6)
	style.content_margin_left = 12
	style.content_margin_right = 12
	style.content_margin_top = 8
	style.content_margin_bottom = 8
	add_theme_stylebox_override("panel", style)

	var vbox := VBoxContainer.new()
	vbox.add_theme_constant_override("separation", 8)
	add_child(vbox)

	# Title
	var title := Label.new()
	title.text = "CONTACT TRACKER"
	title.add_theme_font_size_override("font_size", 16)
	title.add_theme_color_override("font_color", COLOR_TEXT)
	title.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	vbox.add_child(title)

	# 4x4 sector grid
	var grid := GridContainer.new()
	grid.columns = 4
	grid.add_theme_constant_override("h_separation", 4)
	grid.add_theme_constant_override("v_separation", 4)
	vbox.add_child(grid)

	_grid_labels.clear()
	for r in range(4):
		var row: Array = []
		for c in range(4):
			var cell := Label.new()
			cell.text = "·"
			cell.add_theme_font_size_override("font_size", 18)
			cell.add_theme_color_override("font_color", COLOR_CLEAR)
			cell.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
			cell.custom_minimum_size = Vector2(36, 28)
			grid.add_child(cell)
			row.append(cell)
		_grid_labels.append(row)

	# Action buttons
	var btn_box := HBoxContainer.new()
	btn_box.add_theme_constant_override("separation", 6)
	vbox.add_child(btn_box)

	var roll_contact_btn := Button.new()
	roll_contact_btn.text = "Roll Contact"
	roll_contact_btn.custom_minimum_size.y = 32
	roll_contact_btn.pressed.connect(_on_roll_contact)
	btn_box.add_child(roll_contact_btn)

	var reveal_btn := Button.new()
	reveal_btn.text = "Reveal Nearest"
	reveal_btn.custom_minimum_size.y = 32
	reveal_btn.pressed.connect(_on_reveal_nearest)
	btn_box.add_child(reveal_btn)

	var spawn_btn := Button.new()
	spawn_btn.text = "Priority Spawn"
	spawn_btn.custom_minimum_size.y = 32
	spawn_btn.pressed.connect(_on_priority_spawning)
	btn_box.add_child(spawn_btn)

	# Marker list
	_marker_list = VBoxContainer.new()
	_marker_list.add_theme_constant_override("separation", 4)
	vbox.add_child(_marker_list)

	# Log
	_log_container = VBoxContainer.new()
	_log_container.add_theme_constant_override("separation", 2)
	vbox.add_child(_log_container)


func _refresh_display() -> void:
	# Reset grid
	for r in range(4):
		for c in range(4):
			if r < _grid_labels.size() and c < _grid_labels[r].size():
				var cell: Label = _grid_labels[r][c]
				cell.text = "·"
				cell.add_theme_color_override("font_color", COLOR_CLEAR)

	# Place contact markers
	for marker in _contact_markers:
		if marker is not Dictionary:
			continue
		var sector: Dictionary = marker.get("sector", {})
		var row: int = sector.get("row", 0)
		var col: int = sector.get("col", 0)
		if row < _grid_labels.size() and col < _grid_labels[row].size():
			var cell: Label = _grid_labels[row][col]
			if marker.get("revealed", false):
				cell.text = "X"
				cell.add_theme_color_override("font_color", COLOR_DANGER)
			else:
				cell.text = "?"
				cell.add_theme_color_override("font_color", COLOR_BLIP)

	# Place tactical locations
	for loc in _tactical_locations:
		if loc is not Dictionary:
			continue
		var sector: Dictionary = loc.get("sector", {})
		var row: int = sector.get("row", 0)
		var col: int = sector.get("col", 0)
		if row < _grid_labels.size() and col < _grid_labels[row].size():
			var cell: Label = _grid_labels[row][col]
			if cell.text == "·":
				cell.text = "T"
				cell.add_theme_color_override("font_color", COLOR_SUCCESS)

	# Update marker list
	for child in _marker_list.get_children():
		child.queue_free()

	for marker in _contact_markers:
		if marker is not Dictionary:
			continue
		var lbl := Label.new()
		var sector: Dictionary = marker.get("sector", {})
		if marker.get("revealed", false):
			lbl.text = "%s: REVEALED — %s (x%d)" % [
				marker.get("id", "?"),
				marker.get("enemy_type", "Unknown"),
				marker.get("enemy_count", 0)]
			lbl.add_theme_color_override("font_color", COLOR_DANGER)
		else:
			lbl.text = "%s: Sector (%d,%d) — Unidentified" % [
				marker.get("id", "?"),
				sector.get("row", 0), sector.get("col", 0)]
			lbl.add_theme_color_override("font_color", COLOR_WARNING)
		lbl.add_theme_font_size_override("font_size", 12)
		_marker_list.add_child(lbl)


func _on_roll_contact() -> void:
	## Roll on the D6 contact table for each unrevealed marker.
	if not _enemy_generator:
		_add_log("No enemy generator available")
		return

	var contact_result: Dictionary = _enemy_generator.roll_contact_table()
	var entry: Dictionary = contact_result.get("result", {})
	var result_type: String = entry.get("type", "stay_frosty")

	match result_type:
		"stay_frosty":
			_add_log("Stay frosty — no movement detected")
		"movement":
			_add_log("Movement detected — markers shift position")
			_move_random_marker()
		"contact":
			_add_log("CONTACT! Nearest marker revealed!")
			_reveal_next_marker()


func _on_reveal_nearest() -> void:
	_reveal_next_marker()


func _on_priority_spawning() -> void:
	## Roll Priority Spawning dice (D6s equal to Priority).
	var priority: int = _battle_context.get("priority", 1)
	if not _enemy_generator:
		_add_log("No enemy generator available")
		return

	var new_contacts: int = _enemy_generator.roll_priority_spawning(priority)

	if new_contacts > 0:
		_add_log("Priority Spawning: %d new contact(s)!" % new_contacts)
		for i in range(new_contacts):
			_add_contact_marker()
		priority_spawning_result.emit(new_contacts)
	else:
		_add_log("Priority Spawning: All clear")


func _reveal_next_marker() -> void:
	for marker in _contact_markers:
		if marker is Dictionary and not marker.get("revealed", false):
			marker.revealed = true
			_encounter_count += 1

			if _enemy_generator:
				var reveal: Dictionary = _enemy_generator.reveal_contact(_encounter_count)
				var enemy_name: String = reveal.get("enemy_type", {}).get("name", "Unknown Hostiles")
				var enemy_count: int = reveal.get("count", 0)
				marker.enemy_type = enemy_name
				marker.enemy_count = enemy_count
				contact_revealed.emit(marker.get("id", ""), reveal)
				_add_log("REVEALED: %s — %d x %s" % [
					marker.get("id", "?"), enemy_count, enemy_name])
			else:
				_add_log("REVEALED: %s (no enemy data)" % marker.get("id", "?"))

			_refresh_display()
			return

	_add_log("No unrevealed markers remaining")


func _move_random_marker() -> void:
	var unrevealed: Array = []
	for marker in _contact_markers:
		if marker is Dictionary and not marker.get("revealed", false):
			unrevealed.append(marker)

	if unrevealed.is_empty():
		return

	var marker: Dictionary = unrevealed[randi() % unrevealed.size()]
	var old_sector: Dictionary = marker.get("sector", {})
	var new_row: int = clampi(old_sector.get("row", 0) + (randi() % 3) - 1, 0, 3)
	var new_col: int = clampi(old_sector.get("col", 0) + (randi() % 3) - 1, 0, 3)
	marker.sector = {"row": new_row, "col": new_col}

	contact_moved.emit(marker.get("id", ""), old_sector, marker.sector)
	_refresh_display()


func _add_contact_marker() -> void:
	var new_id: String = "contact_%d" % (_contact_markers.size() + 1)
	# Spawn from a random edge
	var edge: int = randi() % 4
	var sector: Dictionary
	match edge:
		0: sector = {"row": 0, "col": randi() % 4}
		1: sector = {"row": randi() % 4, "col": 3}
		2: sector = {"row": 3, "col": randi() % 4}
		_: sector = {"row": randi() % 4, "col": 0}

	_contact_markers.append({
		"id": new_id,
		"sector": sector,
		"revealed": false,
		"enemy_type": "",
		"enemy_count": 0
	})
	_refresh_display()


func _add_log(text: String) -> void:
	var lbl := Label.new()
	lbl.text = "> " + text
	lbl.add_theme_font_size_override("font_size", 11)
	lbl.add_theme_color_override("font_color", COLOR_TEXT_SEC)
	lbl.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	_log_container.add_child(lbl)

	# Keep log manageable
	while _log_container.get_child_count() > 8:
		_log_container.get_child(0).queue_free()
