class_name RumorTrackingSystem
extends Node

## Rumor Tracking System - Five Parsecs Core Rules p.85
## Manages quest rumors with full persistence, source tracking, and mission linkage
## Supports quest progression stages from expanded_quest_progressions.json

# ============ SIGNALS ============
signal rumor_acquired(rumor: Dictionary)
signal rumor_consumed(rumor: Dictionary, quest_id: String)
signal quest_progressed(quest_id: String, new_stage: int)
signal quest_finale_triggered(quest_id: String)

# ============ ENUMS ============
enum RumorSource {
	BACKGROUND,        # From character background at creation
	MOTIVATION,        # From character motivation at creation
	ELITE_ENEMY,       # Dropped by elite enemy in battle
	BATTLE_LOOT,       # Found in post-battle loot (Quest Rumor result)
	PATRON_INTEL,      # Given by patron as job reward
	CONTACT,           # Acquired from world contacts
	STORY_EVENT,       # Generated by story track events
	INVESTIGATION      # Purchased via crew task
}

enum QuestStage {
	INITIAL_LEAD,       # Stage 1: Just found the quest
	FOLLOWING_TRAIL,    # Stage 2: Making progress
	MAJOR_BREAKTHROUGH, # Stage 3: Significant discovery
	FINAL_CONFRONTATION # Stage 4: Finale ready
}

# ============ CONSTANTS ============
const QUEST_PROGRESSIONS_PATH := "res://data/expanded_quest_progressions.json"

# Roll thresholds for quest progression (Core Rules p.119)
const DEAD_END_THRESHOLD := 3      # Roll ≤3: No progress
const PROGRESS_THRESHOLD := 6      # Roll 4-6: Gain rumor
const FINALE_THRESHOLD := 7        # Roll 7+: Finale ready

# ============ STATE ============
var rumors: Array[Dictionary] = []           # All tracked rumors with metadata
var active_quests: Array[Dictionary] = []    # Currently active quests
var completed_quests: Array[Dictionary] = [] # Completed quest archive
var quest_progressions: Dictionary = {}      # Loaded quest progression data
var _next_rumor_id: int = 0
var _next_quest_id: int = 0

# ============ INITIALIZATION ============
func _ready() -> void:
	_load_quest_progressions()

func _load_quest_progressions() -> void:
	## Load quest progression stages from JSON
	var file := FileAccess.open(QUEST_PROGRESSIONS_PATH, FileAccess.READ)
	if not file:
		push_warning("RumorTrackingSystem: Could not load quest progressions from %s" % QUEST_PROGRESSIONS_PATH)
		return

	var json_text := file.get_as_text()
	file.close()

	var parsed = JSON.parse_string(json_text)
	if parsed is Dictionary:
		quest_progressions = parsed
		pass

# ============ RUMOR ACQUISITION ============

func add_rumor(source: RumorSource, description: String, metadata: Dictionary = {}) -> Dictionary:
	## Add a new rumor with full tracking metadata
	##
	## Args:
	## source: Where the rumor came from (RumorSource enum)
	## description: Text description of the rumor
	## metadata: Additional data (character_id, enemy_type, patron_id, etc.)
	##
	## Returns:
	## The created rumor dictionary
	var rumor := {
		"id": "rumor_%d" % _next_rumor_id,
		"source": source,
		"source_name": RumorSource.keys()[source],
		"description": description,
		"turn_acquired": _get_current_turn(),
		"linked_quest_id": "",
		"metadata": metadata.duplicate(),
		"is_consumed": false
	}

	_next_rumor_id += 1
	rumors.append(rumor)

	rumor_acquired.emit(rumor)

	return rumor

func add_rumor_from_background(character_name: String, background_name: String) -> Dictionary:
	## Add a rumor from character background during creation
	var desc := "Intel from %s's past as %s" % [character_name, background_name]
	return add_rumor(RumorSource.BACKGROUND, desc, {
		"character_name": character_name,
		"background": background_name
	})

func add_rumor_from_motivation(character_name: String, motivation_name: String) -> Dictionary:
	## Add a rumor from character motivation during creation
	var desc := "Lead from %s's motivation: %s" % [character_name, motivation_name]
	return add_rumor(RumorSource.MOTIVATION, desc, {
		"character_name": character_name,
		"motivation": motivation_name
	})

func add_rumor_from_elite_enemy(enemy_type: String, enemy_rank: String) -> Dictionary:
	## Add a rumor dropped by elite enemy in battle
	var desc := "Data recovered from defeated %s %s" % [enemy_rank, enemy_type]
	return add_rumor(RumorSource.ELITE_ENEMY, desc, {
		"enemy_type": enemy_type,
		"enemy_rank": enemy_rank
	})

func add_rumor_from_loot() -> Dictionary:
	## Add a rumor from battlefield finds (Quest Rumor result)
	var desc := "Curious data stick found among battlefield debris"
	return add_rumor(RumorSource.BATTLE_LOOT, desc, {})

func add_rumor_from_patron(patron_name: String, job_name: String) -> Dictionary:
	## Add a rumor given by patron as job reward
	var desc := "Intel provided by %s after completing '%s'" % [patron_name, job_name]
	return add_rumor(RumorSource.PATRON_INTEL, desc, {
		"patron_name": patron_name,
		"job_name": job_name
	})

# ============ RUMOR QUERIES ============

func get_active_rumors() -> Array[Dictionary]:
	## Get all unconsumed rumors
	var active: Array[Dictionary] = []
	for rumor in rumors:
		if not rumor.get("is_consumed", false):
			active.append(rumor)
	return active

func get_rumor_count() -> int:
	## Get count of active (unconsumed) rumors
	return get_active_rumors().size()

func get_rumors_by_source(source: RumorSource) -> Array[Dictionary]:
	## Get all rumors from a specific source
	var matching: Array[Dictionary] = []
	for rumor in rumors:
		if rumor.get("source") == source and not rumor.get("is_consumed", false):
			matching.append(rumor)
	return matching

# ============ QUEST GENERATION ============

func try_generate_quest() -> Dictionary:
	## Roll D6 - if <= rumor count, generate quest
	## Returns: Quest dictionary if generated, empty dict if failed
	var rumor_count := get_rumor_count()
	if rumor_count == 0:
		return {}

	var roll := randi() % 6 + 1

	if roll <= rumor_count:
		# Success! Create quest from rumors
		return _create_quest_from_rumors()

	return {}

func _create_quest_from_rumors() -> Dictionary:
	## Create a new quest from accumulated rumors
	var active_rumors := get_active_rumors()

	# Consume all rumors for quest creation
	for rumor in active_rumors:
		rumor["is_consumed"] = true
		rumor["linked_quest_id"] = "quest_%d" % _next_quest_id

	var quest := {
		"id": "quest_%d" % _next_quest_id,
		"name": _generate_quest_name(active_rumors),
		"description": _generate_quest_description(active_rumors),
		"type": _determine_quest_type(active_rumors),
		"current_stage": QuestStage.INITIAL_LEAD,
		"quest_rumors": [],  # Rumors collected during quest (for progression)
		"missions_completed": [],  # Linked mission IDs
		"turn_started": _get_current_turn(),
		"turn_completed": -1,
		"source_rumors": active_rumors.duplicate(true),  # Archive of source rumors
		"rewards": _get_stage_rewards(QuestStage.INITIAL_LEAD),
		"is_finale_ready": false,
		"is_completed": false
	}

	_next_quest_id += 1
	active_quests.append(quest)

	quest_progressed.emit(quest.id, quest.current_stage)

	return quest

func _generate_quest_name(source_rumors: Array) -> String:
	## Generate quest name based on rumor sources
	var prefixes := ["The Lost", "Hidden", "Ancient", "Stolen", "Mysterious", "Dangerous", "Forgotten", "Secret"]
	var subjects := ["Artifact", "Cargo", "Data", "Weapon", "Ship", "Coordinates", "Relic", "Cache"]

	# Customize based on rumor sources
	if source_rumors.any(func(r): return r.get("source") == RumorSource.ELITE_ENEMY):
		prefixes.append_array(["The Hunted", "Recovered", "Pilfered"])
	if source_rumors.any(func(r): return r.get("source") == RumorSource.PATRON_INTEL):
		prefixes.append_array(["The Client's", "Contracted", "Priority"])

	return "%s %s" % [prefixes[randi() % prefixes.size()], subjects[randi() % subjects.size()]]

func _generate_quest_description(source_rumors: Array) -> String:
	## Generate quest description
	var descriptions := [
		"Your accumulated intel has revealed the location of something valuable.",
		"Multiple sources confirm a significant opportunity awaits.",
		"The rumors point to a dangerous but potentially rewarding mission.",
		"Cross-referencing your leads has uncovered a hidden threat."
	]
	return descriptions[randi() % descriptions.size()]

func _determine_quest_type(source_rumors: Array) -> String:
	## Determine quest type based on rumor sources
	var types := ["retrieve", "eliminate", "escort", "investigate", "defend"]

	# Weight types based on rumor sources
	if source_rumors.any(func(r): return r.get("source") == RumorSource.ELITE_ENEMY):
		return "eliminate"  # Enemy-sourced rumors lead to combat quests
	if source_rumors.any(func(r): return r.get("source") == RumorSource.PATRON_INTEL):
		return ["retrieve", "escort"].pick_random()

	return types[randi() % types.size()]

# ============ QUEST PROGRESSION ============

func add_quest_rumor(quest_id: String) -> bool:
	## Add a quest rumor to an active quest (for progression rolls)
	## Returns: true if rumor was added, false if quest not found
	for quest in active_quests:
		if quest.id == quest_id:
			quest.quest_rumors.append({
				"turn_acquired": _get_current_turn(),
				"source": "quest_progress"
			})
			return true

	push_warning("RumorTrackingSystem: Quest not found: %s" % quest_id)
	return false

func roll_quest_progress(quest_id: String, battle_won: bool = true) -> Dictionary:
	## Roll for quest progress after a battle
	## Returns: Dictionary with roll results and outcome
	var quest: Dictionary = {}
	for q in active_quests:
		if q.id == quest_id:
			quest = q
			break

	if quest.is_empty():
		push_warning("RumorTrackingSystem: Cannot roll progress - quest not found: %s" % quest_id)
		return {}

	# Roll: D6 + Quest Rumors + Modifier
	var base_roll: int = randi() % 6 + 1
	var rumors_array: Array = quest.get("quest_rumors", [])
	var quest_rumors: int = rumors_array.size()
	var modifier: int = 0 if battle_won else -2  # -2 if battle lost
	var total: int = base_roll + quest_rumors + modifier

	var outcome := "dead_end"
	var gained_rumor := false
	var finale_ready := false

	if total >= FINALE_THRESHOLD:
		outcome = "finale_ready"
		finale_ready = true
		quest["is_finale_ready"] = true
		quest_finale_triggered.emit(quest_id)
	elif total > DEAD_END_THRESHOLD:
		outcome = "progress"
		gained_rumor = true
		add_quest_rumor(quest_id)
	else:
		pass

	return {
		"quest_id": quest_id,
		"quest_name": quest.name,
		"base_roll": base_roll,
		"quest_rumors": quest_rumors,
		"modifier": modifier,
		"total": total,
		"outcome": outcome,
		"gained_rumor": gained_rumor,
		"finale_ready": finale_ready
	}

func advance_quest_stage(quest_id: String) -> bool:
	## Advance quest to next stage after completing stage requirements
	## Returns: true if advanced, false if already at final stage
	for quest in active_quests:
		if quest.id == quest_id:
			var current: int = quest.get("current_stage", QuestStage.INITIAL_LEAD)
			if current < QuestStage.FINAL_CONFRONTATION:
				quest["current_stage"] = current + 1
				quest["rewards"] = _get_stage_rewards(quest["current_stage"])
				quest_progressed.emit(quest_id, quest["current_stage"])
				return true
			return false
	return false

func complete_quest(quest_id: String, success: bool = true) -> Dictionary:
	## Complete a quest and calculate final rewards
	## Returns: Final rewards dictionary
	for i in range(active_quests.size()):
		if active_quests[i].id == quest_id:
			var quest := active_quests[i]
			quest["is_completed"] = true
			quest["turn_completed"] = _get_current_turn()
			quest["success"] = success

			# Calculate final rewards
			var rewards := _calculate_final_rewards(quest, success)
			quest["final_rewards"] = rewards

			# Move to completed quests
			completed_quests.append(quest)
			active_quests.remove_at(i)

			return rewards

	return {}

func _get_stage_rewards(stage: QuestStage) -> Dictionary:
	## Get rewards for completing a quest stage
	var stages: Array = quest_progressions.get("quest_stages", [])
	if stage < stages.size():
		return stages[stage].get("rewards", {})

	# Fallback if JSON not loaded
	match stage:
		QuestStage.INITIAL_LEAD:
			return {"credits": "1D6 x 10", "story_points": 1}
		QuestStage.FOLLOWING_TRAIL:
			return {"credits": "2D6 x 10", "story_points": 1, "gear": "Random item"}
		QuestStage.MAJOR_BREAKTHROUGH:
			return {"credits": "3D6 x 10", "story_points": 2, "gear": "Rare item"}
		QuestStage.FINAL_CONFRONTATION:
			return {"credits": "5D6 x 10", "story_points": 3, "gear": "Unique item", "reputation": 2}

	return {}

func _calculate_final_rewards(quest: Dictionary, success: bool) -> Dictionary:
	## Calculate final quest rewards based on stage and success
	if not success:
		return {"credits": 0, "story_points": 0}

	var stage: int = quest.get("current_stage", QuestStage.INITIAL_LEAD)
	var base_rewards := _get_stage_rewards(stage)

	# Convert dice notation to actual values
	var credits_formula: String = base_rewards.get("credits", "1D6 x 10")
	var credits := _roll_dice_formula(credits_formula)

	return {
		"credits": credits,
		"story_points": base_rewards.get("story_points", 1),
		"gear": base_rewards.get("gear", ""),
		"reputation": base_rewards.get("reputation", 0)
	}

func _roll_dice_formula(formula: String) -> int:
	## Roll dice formula like '2D6 x 10'
	# Parse patterns like "2D6 x 10" or "1D6 x 10"
	var regex := RegEx.new()
	regex.compile(r"(\d+)D(\d+)(?:\s*x\s*(\d+))?")
	var match := regex.search(formula)

	if match:
		var num_dice := int(match.get_string(1))
		var die_size := int(match.get_string(2))
		var multiplier := 1
		if match.get_string(3) != "":
			multiplier = int(match.get_string(3))

		var total := 0
		for _i in range(num_dice):
			total += randi() % die_size + 1

		return total * multiplier

	return 0

# ============ MISSION LINKING ============

func link_mission_to_quest(mission_id: String, quest_id: String) -> bool:
	## Link a completed mission to a quest for tracking
	for quest in active_quests:
		if quest.id == quest_id:
			if not quest.has("missions_completed"):
				quest["missions_completed"] = []
			quest["missions_completed"].append(mission_id)
			return true
	return false

# ============ HELPERS ============

func _get_current_turn() -> int:
	## Get current campaign turn
	var game_state := get_node_or_null("/root/GameState")
	if game_state and "current_campaign" in game_state and game_state.current_campaign:
		return game_state.current_campaign.get("campaign_turn", 0)
	return 0

# ============ SERIALIZATION ============

func serialize() -> Dictionary:
	## Serialize full rumor tracking state
	return {
		"rumors": rumors.duplicate(true),
		"active_quests": active_quests.duplicate(true),
		"completed_quests": completed_quests.duplicate(true),
		"next_rumor_id": _next_rumor_id,
		"next_quest_id": _next_quest_id
	}

func deserialize(data: Dictionary) -> void:
	## Restore rumor tracking state from saved data
	rumors.clear()
	for rumor_data in data.get("rumors", []):
		var rumor: Dictionary = rumor_data.duplicate(true)
		rumors.append(rumor)

	active_quests.clear()
	for quest_data in data.get("active_quests", []):
		var quest: Dictionary = quest_data.duplicate(true)
		active_quests.append(quest)

	completed_quests.clear()
	for quest_data in data.get("completed_quests", []):
		var quest: Dictionary = quest_data.duplicate(true)
		completed_quests.append(quest)

	_next_rumor_id = data.get("next_rumor_id", rumors.size())
	_next_quest_id = data.get("next_quest_id", active_quests.size() + completed_quests.size())

	pass

func get_active_quest() -> Dictionary:
	## Get the currently active quest (first one if multiple)
	if active_quests.size() > 0:
		return active_quests[0]
	return {}

func has_active_quest() -> bool:
	## Check if there's an active quest
	return active_quests.size() > 0
