	# Skip signal monitoring to prevent Dictionary corruption
	# assert_signal(_error_logger).is_emitted("error_logged")  # REMOVED - causes Dictionary corruption
	# assert_signal(_error_logger).is_emitted("warning_logged")  # REMOVED - causes Dictionary corruption
	# assert_signal(_error_logger).is_emitted("info_logged")  # REMOVED - causes Dictionary corruption
	# assert_signal(_error_logger).is_emitted("log_cleared")  # REMOVED - causes Dictionary corruption
	# assert_signal(_error_logger).is_emitted("log_exported")  # REMOVED - causes Dictionary corruption
	# assert_signal(_error_logger).is_emitted("log_imported")  # REMOVED - causes Dictionary corruption
	# assert_signal(_error_logger).is_emitted("log_filtered")  # REMOVED - causes Dictionary corruption
	# assert_signal(_error_logger).is_emitted("log_sorted")  # REMOVED - causes Dictionary corruption
	# Test state directly instead of signal emission 