extends Node

## TaloAnalyticsAdapter — bridges in-memory CampaignAnalytics events to Talo telemetry.
##
## Subscribes to `CampaignAnalytics.analytics_event_recorded` and, if user consent
## is granted via `LegalConsentManager.get_analytics_consent()`, forwards events
## to the Talo SDK at `/root/Talo`.
##
## ## Null-safe pre-install behavior
##
## This adapter is intentionally written to handle three states gracefully:
##
## 1. **Talo plugin NOT yet installed** (Phase 0.6 → Phase 1 transition window):
##    `/root/Talo` is null. The adapter subscribes to CampaignAnalytics events
##    but silently drops them. No errors, no warnings.
## 2. **Talo plugin installed, analytics_consent == false**:
##    Events are dropped at the consent gate before any Talo call.
## 3. **Talo plugin installed, analytics_consent == true**:
##    Events forwarded to `Talo.events.track(event_type, flattened_payload)`
##    with a session UUID that contains zero PII.
##
## ## Privacy contract
##
## - No personally identifying information is forwarded. The session ID is the
##   anonymous UUID generated by `CampaignAnalytics._generate_session_id()`.
## - Nested dicts in event payloads are flattened (Talo property values are
##   primitives) and any keys that look like PII (`name`, `email`, `id`) are
##   filtered out as a defense-in-depth measure.
## - Consent revocation is real-time: if the user toggles analytics OFF
##   mid-session, subsequent events are dropped.
##
## ## Registration
##
## Registered as autoload AFTER `LegalConsentManager` and `CampaignAnalytics`
## (the adapter depends on both). Talo's own `Talo` autoload is registered by
## the Talo plugin's `EditorPlugin._enter_tree()` and parses before manual
## autoloads, so by the time TaloAnalyticsAdapter._ready() runs, /root/Talo
## either exists (plugin enabled) or doesn't (plugin not yet installed).
##
## See `docs/testing/phase-1-prep/TALO_ADAPTER_DESIGN.md` for the design notes.

const PII_KEY_PATTERNS := ["name", "email", "user_id", "ip", "address", "phone"]
const ANON_ID_FILE := "user://talo_anonymous_id.cfg"
const IDENTIFY_SERVICE := "username"

var _consent_mgr: Node = null
var _campaign_analytics: Node = null
var _talo: Node = null
var _connected: bool = false
var _identified: bool = false
var _anonymous_id: String = ""


func _ready() -> void:
	_consent_mgr = get_node_or_null("/root/LegalConsentManager")
	_campaign_analytics = get_node_or_null("/root/CampaignAnalytics")
	_talo = get_node_or_null("/root/Talo")

	if _campaign_analytics == null:
		push_warning("TaloAnalyticsAdapter: CampaignAnalytics autoload not found — adapter inert.")
		return

	if not _campaign_analytics.has_signal("analytics_event_recorded"):
		push_warning("TaloAnalyticsAdapter: CampaignAnalytics has no analytics_event_recorded signal — adapter inert.")
		return

	_campaign_analytics.analytics_event_recorded.connect(_on_analytics_event)
	_connected = true

	# React to consent toggles in real-time: opt-in triggers identify, opt-out tears it down.
	if _consent_mgr and _consent_mgr.has_signal("consent_updated"):
		_consent_mgr.consent_updated.connect(_on_consent_updated)

	if _talo == null:
		# Plugin not yet installed; silent no-op until install + restart.
		print("TaloAnalyticsAdapter: subscribed to CampaignAnalytics; Talo plugin not detected (will pass-through silently until installed).")
	else:
		print("TaloAnalyticsAdapter: subscribed; Talo plugin detected at /root/Talo; events forwarded when consent granted.")


func _on_analytics_event(event_type: String, data: Dictionary) -> void:
	if not _consent_granted():
		return
	if not _talo_ready():
		return

	# Talo events.track requires identity_check() == OK or it silently drops the event
	# (see addons/talo/apis/events_api.gd:43). Identify lazily on first event after consent.
	if not _identified:
		await _identify_async()
		if not _identified:
			return

	var payload := _sanitize_and_flatten(data)
	# Tag every event with the anonymous session ID for cross-event correlation.
	if _campaign_analytics and _campaign_analytics.session_data is Dictionary:
		var session_id: Variant = _campaign_analytics.session_data.get("session_id")
		if session_id is String:
			payload["session_id"] = session_id

	_talo.events.track(event_type, payload)


func _on_consent_updated() -> void:
	## Reacts to LegalConsentManager.consent_updated. Opt-in triggers identify;
	## opt-out clears identity AND deletes the persisted anonymous ID file
	## so a future re-grant generates a fresh player record (correct GDPR behavior).
	if not _talo_ready():
		return

	var consent_now := _consent_granted()

	if consent_now and not _identified:
		await _identify_async()
	elif not consent_now and _identified:
		_clear_identity_and_delete_id()


func _identify_async() -> void:
	## Identifies the anonymous player with Talo using a stable per-install identifier.
	## Async because Talo.players.identify makes an HTTP round-trip.
	if _talo == null or _talo.get("players") == null:
		return

	var anon_id := _get_or_create_anonymous_id()
	if anon_id.is_empty():
		return

	var player: Variant = await _talo.players.identify(IDENTIFY_SERVICE, anon_id)
	if player != null:
		_identified = true
		print("TaloAnalyticsAdapter: identified anonymously; events will now flow.")
	else:
		push_warning("TaloAnalyticsAdapter: identify failed; events will be retried on next call.")


func _get_or_create_anonymous_id() -> String:
	## Returns the persisted anonymous identifier for this install, generating
	## one on first use. Stored at user://talo_anonymous_id.cfg so the same
	## "player" persists across launches for accurate retention analytics.
	## File only exists when consent has been granted at least once — deleting
	## it on consent revocation severs the device-to-Talo correlation.
	if not _anonymous_id.is_empty():
		return _anonymous_id

	var config := ConfigFile.new()
	if FileAccess.file_exists(ANON_ID_FILE):
		var err := config.load(ANON_ID_FILE)
		if err == OK:
			_anonymous_id = str(config.get_value("identity", "anonymous_id", ""))
			if not _anonymous_id.is_empty():
				return _anonymous_id

	# Generate a fresh 32-char hex identifier (16 random bytes).
	var crypto := Crypto.new()
	var bytes := crypto.generate_random_bytes(16)
	_anonymous_id = bytes.hex_encode()
	config.set_value("identity", "anonymous_id", _anonymous_id)
	config.set_value("identity", "created_at", Time.get_datetime_string_from_system(true))
	config.save(ANON_ID_FILE)
	return _anonymous_id


func _clear_identity_and_delete_id() -> void:
	## Tears down the Talo player identity AND deletes the persisted ID file.
	## Pair with LegalConsentManager.delete_all_user_data() flow for full GDPR
	## compliance: revoking consent should leave no trace on the client.
	if _talo and _talo.get("players") != null:
		_talo.players.clear_identity()

	var dir := DirAccess.open("user://")
	if dir and dir.file_exists("talo_anonymous_id.cfg"):
		dir.remove("talo_anonymous_id.cfg")

	_identified = false
	_anonymous_id = ""


func _consent_granted() -> bool:
	if _consent_mgr == null:
		return false
	if not _consent_mgr.has_method("get_analytics_consent"):
		return false
	return bool(_consent_mgr.get_analytics_consent())


func _talo_ready() -> bool:
	# Re-check on each event so a late plugin install / disable is honored.
	if _talo == null:
		_talo = get_node_or_null("/root/Talo")
	if _talo == null:
		return false
	if not _talo.has_method("get") or _talo.get("events") == null:
		return false
	return true


func _sanitize_and_flatten(data: Dictionary) -> Dictionary:
	var out: Dictionary = {}
	for key: Variant in data.keys():
		var key_str := str(key).to_lower()
		# Defense-in-depth PII filter — even if a caller accidentally passes a name field.
		var is_pii := false
		for pattern: String in PII_KEY_PATTERNS:
			if key_str.find(pattern) >= 0:
				is_pii = true
				break
		if is_pii:
			continue

		var value: Variant = data[key]
		# Flatten nested dicts one level (Talo properties are primitives).
		if value is Dictionary:
			for nested_key: Variant in value.keys():
				out[str(key) + "." + str(nested_key)] = value[nested_key]
		elif value is Array:
			out[str(key)] = JSON.stringify(value)
		else:
			out[str(key)] = value
	return out


## Diagnostics — useful during alpha for debugging the consent gate live.

func is_active() -> bool:
	## Returns true when the adapter is wired AND ready to forward events
	## (Talo present + consent granted + identified). Used by Settings → About diagnostics.
	return _connected and _consent_granted() and _talo_ready() and _identified


func get_status_string() -> String:
	if not _connected:
		return "Inactive (CampaignAnalytics signal not connected)"
	if not _talo_ready():
		return "Inactive (Talo plugin not detected)"
	if not _consent_granted():
		return "Inactive (analytics consent OFF)"
	if not _identified:
		return "Pending (Talo identify will run on first event after consent)"
	return "Active (forwarding events to Talo)"
